name: Update webshots

on:
  pull_request:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repository
        uses: actions/checkout@v2

      - name: Use Python 3.8+
        uses: actions/setup-python@v2
        with:
          python-version: '^3.8'

      - name: Install h5py dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y libhdf5-dev
          python -m pip install 'numpy<1.19.4'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r tools/requirements.txt

      - name: Run webshots script
        run: xvfb-run python tools/make_webshots.py

      - name: Commit changes
        if: github.event_name == 'schedule'
        run: |
          git config --global user.email "team@dandiarchive.org"
          git config --global user.name "DANDI Bot"

          git add .
          if ! git diff --quiet --cached
          then git commit -m "Automatically update webshots"
               git push
          else echo "No changes to commit"
          fi

# vim:set sts=2:
